### when running the server you can test using REST Client for Visual Studio Code
### in this case we are testing the index / 

### LOCAL USER
GET http://localhost:8787/users/v1


### LIVE USER
GET https://notiftool-server.mochi-project.workers.dev/users



### AUTH
GET http://localhost:8787/auth/v1/auth

### AUTH /auth/v1
GET http://localhost:8787/auth/v1/session


### AUTH /auth/v1
GET http://localhost:8787/partyusers/NIgWNMNVlmEXDxQhd2BYuMhJPMvcpS2C


### CREATE ORGANIZATION
POST http://localhost:8787/organizations HTTP/1.1
content-type: application/json

{   
    "party_uuid": "ad5a0626-9b8a-460b-9bbd-960cf505e2ed",
    "name": "JustXYZ1",
    "status": "active",
    "author_party_uuid": "ad5a0626-9b8a-460b-9bbd-960cf505e2ed"
}


### GET FORMS 
GET http://localhost:8787/forms/179f4097-2fac-4de2-ba0c-4132fbb6896a


### CREATE FORMS
POST http://localhost:8787/forms HTTP/1.1
content-type: application/json

{   
    "party_uuid": "179f4097-2fac-4de2-ba0c-4132fbb6896a",
    "name": "A new form",
    "description": "A new form created",
    "json": {}
}